---
# This workflow will build a Docker image and push it to Docker Hub
#
# Required repo secrets:
# - DOCKERHUB_USERNAME
# - DOCKERHUB_TOKEN
#
# Required repo variables:
# - DOCKERHUB_REPONAME


name: Publish image to Docker Hub

on:
  push:
    tags:
      - "v*"


jobs:
  publish:
    name: Publish image
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        env:
          #IMAGE_TAG: ${{ github.ref_type }}-${{ github.ref_name }}
          IMAGE_TAG: ${{ github.ref_name }}
          REPO_NAME: ${{ vars.DOCKERHUB_REPONAME }}
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          set -xe
          
          docker buildx build \
            -t $REGISTRY/$REPO_NAME:$IMAGE_TAG \
            -t $REGISTRY/$REPO_NAME:latest \
            --progress=plain \
            --sbom=true \
            --provenance=true \
            --platform linux/amd64, linux/arm64 \
            -f ./Dockerfile-playwright \
            --push \
            .
          
          echo "image=$REGISTRY/$REPO_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT


#      - name: Build, tag, and push image to Docker Hub
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: ./Dockerfile
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: |
#            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPONAME }}:${{ github.ref_name }}
#            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPONAME }}:latest
#          # Caching
#          #cache-from: type=gha
#          #cache-to: type=gha,mode=max`
